stages:
  - build
  - code-quality

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# -------------------------------
# Stage: build Docker image
# -------------------------------
build-image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    # собираем образ из docker/php/Dockerfile
    - docker build -t $IMAGE_TAG -f docker/php/Dockerfile app/
    - docker push $IMAGE_TAG

# -------------------------------
# Stage: code-quality (все проверки)
# -------------------------------
phpunit:
  stage: code-quality
  image: $IMAGE_TAG
  script:
    - cd app
    - ./vendor/bin/phpunit --testsuite=Unit

phpstan:
  stage: code-quality
  image: $IMAGE_TAG
  script:
    - cd app
    - ./vendor/bin/phpstan analyse Modules

cs-fixer:
  stage: code-quality
  image: $IMAGE_TAG
  script:
    - cd app
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff Modules

rector:
  stage: code-quality
  image: $IMAGE_TAG
  script:
    - cd app
    - ./vendor/bin/rector process --dry-run Modules