name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare .env
        run: |
          cp app/.env.example app/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> app/.env
          echo "APP_ENV=testing" >> app/.env

      - name: Run docker compose up
        run: |
          docker compose up -d php pgsql
          sleep 10

      - name: Install deps + generate key
        run: |
          docker exec app_php bash -c "
            composer install --prefer-dist --no-progress --no-interaction &&
            php artisan key:generate
          "
      - name: Debug paths
        run: |
          docker exec app_php bash -c "
            pwd &&
            ls -la &&
            cd /var/www/app &&
            echo '--- /var/www/app ---' &&
            pwd &&
            ls -la &&
            echo '--- app ---' &&
            ls -la /var/www/app/app || true &&
            echo '--- Modules ---' &&
            ls -la /var/www/app/Modules || true
          "
      - name: Run Tests & Code Quality
        run: |
          docker exec app_php bash -c "
            cd /var/www/app &&
            vendor/bin/pest Modules/*/tests/Feature/ &&
            ./vendor/bin/php-cs-fixer fix Modules --dry-run --diff &&
            ./vendor/bin/phpstan analyse --memory-limit=1G &&
            ./vendor/bin/rector Modules --dry-run
          "

      - name: Tear down
        run: docker compose down