name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Run docker compose up
        run: |
          docker compose -f docker-compose.yml up -d php pgsql
          # Ждём пока Postgres будет готов
          docker exec app_pgsql pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -q

      - name: Run Tests & Code Quality
        run: |
          docker exec app_php bash -c "
            composer install --prefer-dist --no-progress --no-interaction &&
            php artisan test &&
            ./vendor/bin/php-cs-fixer fix --dry-run --diff &&
            ./vendor/bin/phpstan analyse &&
            ./vendor/bin/rector Modules --dry-run
          "

      - name: Tear down
        run: docker compose -f docker-compose.yml down